version: '3'
services:
  database:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: shop
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - database